#Basic java stuff
language: java
jdk:
  - openjdk8

#Install tasks (Can't use apt - outdated)
install:
  - curl -s get.sdkman.io | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - echo sdkman_auto_answer=true > ~/.sdkman/etc/config
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - sdk install gradle 5.5

#Our projects don't have a gradle wrapper
script: gradle build -Prelease

#Don't build untagged branches
branches:
  except:
    - untagged*

#Don't pester me about this stuff
notifications:
  email: false

#Deployment
deploy:
  provider: releases

  #Cleanup deletes the file we build
  skip_cleanup: true

  #Point to the "libs" folder
  file_glob: true
  file: build/libs/*

  #Acceptable repository
  on:
    repo: HelloWorldMinecraft/GraviTree

  #API Key
  api_key:
    secure: ojVqXf86g5YXwYvarbzhkC+1JpRKaA6incAIW1Tx46asx0rOIOGjL430nuOJKVdHDvtYWGAop5CHsdf0eiZIM3hpWsMf9rOJLs3qRT/FUwOpzO3zggwqn7G+zA2EFens8SEYgaWaYy4UKRlbiJ7KGnWxzrr+l10hRCnyvN9ZKerfDU3X39bSsKJVQz+DBjS/7oWeDDHt1Y61cjLbQFY4DjtWXMAffiloJQNxMS8EvN424wG65BzHzLXUFNH6Lc7nKPe4OYbvRxsrXrh/ZtnYwv8HvRrQjmsP0v3aDrQBqiW2RMqNgOgxmfbtlPLuEKwmfkDgeXHTeNORfAIEbaKOHM2zKjtAFdtWWbUfhUKOb+zATri3m3XFTmj463n2QyPFs8Rq4s0rbuZXH4bLgV7Dp8pxAIZxfuaTKzlpoulbObJF/KqsZl9E4SqFqG2SfedFkF1/dXxMzIaYdgjXWjQ+1r1gpVeBAWPWDfKg3000moQ//RrXKpISbAw/zp10yDfGIAGIVQr32DAk3WFicL7MMJ5nVOm+ZnnCW+wClpoIOjNGFCu2PZaeI7RuyQxbX5YHM3FYYSCKDadoarBA9kwxBWShH+Xw9LeQLUxIn8UHruXX8dIlN9aQM3Q3RUhs9mxGfFZmFGbOZJanRjdrNyQBdOvdJoynLYWhGhTKLQVlJXI=
