"All Players Have Permission": true
"Chop Mode Defaunts ON": true
"Messages":
  "Chop Toggle Info": "You can toggle falling tree blocks with /treesfall"
  "Chop Toggle On": "Falling tree blocks enabled."
  "Chop Toggle Off": "Falling tree blocks disabled."
"Players Can Disable": true