name: FancyChat
main: me.ryanhamshire.GraviTree.GraviTree
version: ${project.version}
api-version: "1.13"
authors: [HelloWorld]
commands:
  treesfall:
    description: Toggles tree blocks falling when a tree is chopped.
    usage: /TreesFall
permissions:
  gravitree.chop:
    description: Grants permission to apply gravity to chopped trees.
    default: op