name: ${project.name}
main: me.ryanhamshire.GraviTree.GraviTree
version: ${project.version}
api-version: ${project.apiversion}
authors: [ Username4723 ]
commands:
  treesfall:
    description: Toggles tree blocks falling when a tree is chopped.
    usage: /TreesFall
permissions:
  gravitree.chop:
    description: Grants permission to apply gravity to chopped trees.
    default: op